const Constants = {
  GET_ORGANIZATIONS: 'GET_ORGANIZATIONS',
  ORGANIZATIONS_RECEIVED: 'ORGANIZATIONS_RECEIVED',
  ADD_ORGANIZATION: 'ADD_ORGANIZATION',
  ORGANIZATION_ADDED: 'ORGANIZATION_ADDED',
  GET_ORGANIZATION: 'GET_ORGANIZATION',
  ORGANIZATION_RECEIVED: 'ORGANIZATION_RECEIVED',
}

export default Constants;
